import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google"; // ✅ Import Inter Tight
import "./globals.css";
import { AuthProvider } from "@/components/common/AuthContext";

// ✅ Load the Inter Tight font
const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
  display: "swap", // Optional for better font loading behavior
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interTight.variable} antialiased`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
